export interface LegalResource {
  id: string;
  name: string;
  type: 'legal_aid' | 'public_defender' | 'nonprofit' | 'bar_referral' | 'clinic';
  region: string;
  address: string;
  phone: string;
  website: string;
  description: string;
  serves: string[];
  lat: number;
  lon: number;
}

export const LEGAL_RESOURCES: LegalResource[] = [
  {
    id: 'bala',
    name: 'Bay Area Legal Aid',
    type: 'legal_aid',
    region: 'Bay Area',
    address: '1735 Telegraph Ave, Oakland, CA 94612',
    phone: '415-982-1300',
    website: 'baylegal.org',
    description: 'Free civil legal services for low-income Bay Area residents including housing, public benefits, and immigration.',
    serves: ['housing', 'immigration', 'benefits', 'domestic violence'],
    lat: 37.8112,
    lon: -122.2680,
  },
  {
    id: 'lafla',
    name: 'Legal Aid Foundation of Los Angeles',
    type: 'legal_aid',
    region: 'Los Angeles',
    address: '1550 W 8th St, Los Angeles, CA 90017',
    phone: '213-640-3881',
    website: 'lafla.org',
    description: 'Free legal assistance for LA County\'s poorest residents in housing, immigration, and family law.',
    serves: ['housing', 'immigration', 'family', 'benefits'],
    lat: 34.0522,
    lon: -118.2574,
  },
  {
    id: 'public_counsel',
    name: 'Public Counsel',
    type: 'nonprofit',
    region: 'Los Angeles',
    address: '610 S Ardmore Ave, Los Angeles, CA 90005',
    phone: '213-385-2977',
    website: 'publiccounsel.org',
    description: 'Largest pro bono law firm in the nation. Specializes in children\'s rights, homelessness, and immigration.',
    serves: ['immigration', 'children', 'homelessness', 'veterans'],
    lat: 34.0625,
    lon: -118.3049,
  },
  {
    id: 'bet_tzedek',
    name: 'Bet Tzedek Legal Services',
    type: 'nonprofit',
    region: 'Los Angeles',
    address: '3250 Wilshire Blvd #1300, Los Angeles, CA 90010',
    phone: '323-939-0506',
    website: 'bettzedek.org',
    description: 'Free legal help with elder law, Holocaust survivors, and low-income individuals in Los Angeles.',
    serves: ['elder law', 'employment', 'housing', 'consumer'],
    lat: 34.0598,
    lon: -118.3066,
  },
  {
    id: 'crla',
    name: 'California Rural Legal Assistance',
    type: 'legal_aid',
    region: 'Central Valley & Rural CA',
    address: '631 Howard St #300, San Francisco, CA 94105',
    phone: '415-777-2752',
    website: 'crla.org',
    description: 'Serves low-income people, migrant/seasonal workers, and farm workers in rural California.',
    serves: ['immigration', 'farmworkers', 'housing', 'employment'],
    lat: 37.7869,
    lon: -122.3977,
  },
  {
    id: 'drc',
    name: 'Disability Rights California',
    type: 'nonprofit',
    region: 'Statewide',
    address: '1831 K St, Sacramento, CA 95811',
    phone: '800-776-5746',
    website: 'disabilityrightsca.org',
    description: 'Protects and advocates for the rights of Californians with disabilities.',
    serves: ['disability', 'mental health', 'education', 'housing'],
    lat: 38.5699,
    lon: -121.4782,
  },
  {
    id: 'nlg_sf',
    name: 'National Lawyers Guild — SF Bay Area',
    type: 'nonprofit',
    region: 'Bay Area',
    address: '558 Capp St, San Francisco, CA 94110',
    phone: '415-285-5067',
    website: 'nlgsf.org',
    description: 'Progressive attorneys providing legal support for protest, civil rights, and social justice.',
    serves: ['civil rights', 'immigration', 'protest', 'police misconduct'],
    lat: 37.7512,
    lon: -122.4144,
  },
  {
    id: 'aclu_ca',
    name: 'ACLU of California',
    type: 'nonprofit',
    region: 'Statewide',
    address: '39 Drumm St, San Francisco, CA 94111',
    phone: '415-621-2493',
    website: 'aclu.org/ca',
    description: 'Defends civil liberties including free speech, voting rights, LGBTQ+ rights, and police accountability.',
    serves: ['civil rights', 'LGBTQ+', 'voting', 'criminal justice'],
    lat: 37.7935,
    lon: -122.3994,
  },
  {
    id: 'lsnc',
    name: 'Legal Services of Northern CA',
    type: 'legal_aid',
    region: 'Northern CA',
    address: '517 12th St, Sacramento, CA 95814',
    phone: '916-551-2150',
    website: 'lsnc.net',
    description: 'Free civil legal assistance for low-income residents of Northern California.',
    serves: ['housing', 'family', 'benefits', 'consumer'],
    lat: 38.5795,
    lon: -121.4940,
  },
  {
    id: 'inland_counties',
    name: 'Inland Counties Legal Services',
    type: 'legal_aid',
    region: 'Inland Empire',
    address: '1040 Iowa Ave #109, Riverside, CA 92507',
    phone: '888-245-4257',
    website: 'inlandcountiesls.org',
    description: 'Free legal services for low-income residents of Riverside and San Bernardino counties.',
    serves: ['housing', 'immigration', 'family', 'consumer'],
    lat: 33.9806,
    lon: -117.3755,
  },
  {
    id: 'sd_las',
    name: 'Legal Aid Society of San Diego',
    type: 'legal_aid',
    region: 'San Diego',
    address: '110 S Euclid Ave, San Diego, CA 92114',
    phone: '877-534-2524',
    website: 'lassd.org',
    description: 'Free legal services for San Diego County residents in housing, family, and consumer matters.',
    serves: ['housing', 'family', 'consumer', 'benefits'],
    lat: 32.7157,
    lon: -117.1611,
  },
  {
    id: 'public_defenders',
    name: 'CA Public Defenders Association',
    type: 'public_defender',
    region: 'Statewide',
    address: '1000 G St #800, Sacramento, CA 95814',
    phone: '916-446-1190',
    website: 'cpda.org',
    description: 'Connect with your county public defender for free criminal defense representation.',
    serves: ['criminal defense'],
    lat: 38.5816,
    lon: -121.4944,
  },
];

export type ResourceType = LegalResource['type'];

export const TYPE_LABELS: Record<ResourceType, string> = {
  legal_aid: 'Legal Aid',
  public_defender: 'Public Defender',
  nonprofit: 'Nonprofit',
  bar_referral: 'Bar Referral',
  clinic: 'Legal Clinic',
};
